server:
  port: 8085

spring:
  application:
    name: portfolio-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/portfolio_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:dhoddudb}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
